<?php
/** @var \Mirasvit\Rma\Block\Rma\NewRma\Step2\Additional $block */
?>
<div class="block">
    <div class="block-title">
        <strong><?= __('附加訊息') ?></strong>
    </div>
    <div class="block-content">
        <fieldset class="fieldset">
            <div class="field">
                <div class="control">
                    <textarea name="reply" id="reply" class="input-text"></textarea>
                </div>
            </div>

        </fieldset>
    </div>
</div>