<?php
/* @var $block \Mirasvit\Rma\Block\Rma\View\History */
$messages = $block->getMessages()
?>
<?php if (count($messages)): ?>
    <div class="block">
        <div class="block-title">
            <strong><?= __('RMA History') ?></strong>
        </div>
        <div class="block-content">
            <?php foreach ($messages as $message): ?>
                <div
                    class="rma-message <?php if ($message->getCustomerName()): ?>customer<?php else: ?>user<?php endif ?>">
                    <div class="rma-message-title">
                        <?php if ($message->getCustomerName()): ?>
                            <?= $message->getCustomerName() ?> |
                        <?php elseif ($user = $block->getUser($message)): ?>
                            <?= $user->getName() ?> |
                        <?php endif ?>

                        <?= $block->formatDate($message->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?> <?= $block->formatTime($message->getCreatedAt(), \IntlDateFormatter::SHORT) ?>
                    </div>

                    <div class="rma-message-text">
                        <?= $block->getTextHtml($message) ?>

                        <?php if ($attachments = $block->getAttachments($message)): ?>
                            <?php foreach ($attachments as $attachment): ?>
                                <br><a
                                    href="<?= $block->getAttachmentUrl($attachment) ?>"><?= $attachment->getName() ?></a>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
<?php endif ?>
