<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block account-nav">
    <div class="title">
        <strong><?php /* @escapeNotVerified */ echo __('My Account'); ?></strong>
    </div>

    <div class="account-nav-current"><?php echo __('會員帳戶總覽')?></div>

    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
                <?php echo $block->getChildHtml();?>
            </ul>
        </nav>
    </div>
</div>
<script type="text/javascript">
    requirejs(['jquery'], function ($) {
        $(document).ready(function () {
            $('.account-nav-current').on('click',function(){
                jQuery("body").toggleClass('account-nav-open');
                jQuery(this).toggleClass('account-nav-open');
            });
        });
    });
</script>