<?php
/* @var $block \Mirasvit\Rma\Block\Rma\View\Info */
$rma = $block->getRma();
?>
<div class="block">
    <div class="block-title">
        <strong><?= __('退貨資訊') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-rma-information">
            <table width="100%">
                <tbody>
                <tr>
                    <th><?= __('退貨編號') ?>:</th>
                    <td>#<?= $rma->getIncrementId() ?></td>
                </tr>
                <tr>
                    <th><?= __('訂單編號') ?>:</th>
                    <td>
                        <?php if ($rma->getCustomerId()): ?>
                            <?= $block->getOrderLabel($rma->getOrderId(), $block->getOrderUrl($rma->getOrderId())) ?>
                        <?php else: ?>
                            <?= $block->getOrderLabel($rma->getOrderId()) ?>
                        <?php endif ?>
                        <?= $rma->getIsGift() ? __('(This was a gift)') : '' ?>
                    </td>
                </tr>

                <tr>
                    <th><?= __('日期') ?>:</th>
                    <td><?= $block->formatDate($rma->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></td>
                </tr>
                <tr>
                    <th><?= __('Status') ?>:</th>
                    <td><?= __($block->getStatusName($rma)) ?></td>
                </tr>
                <?php foreach ($block->getCustomFields($rma) as $field): ?>
                    <?php if (!$value = $block->getRmaFieldValue($rma, $field)) {
                        continue;
                    } ?>
                    <tr>
                        <th><?= __($field->getName()) ?>:</th>
                        <td>
                            <?= $value ?>
                        </td>
                    </tr>
                <?php endforeach ?>
                <tr>
                    <th>
                        <?= __('Contact Information') ?>:
                    </th>
                    <td>
                        <?= $rma->getFirstname().' '.$rma->getLastname(); ?>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>