<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style>
    .fwb{
        font-weight:bold;
    }
    .fs16{
        font-size:1.6rem;
    }
</style>

<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <?php
            $helper = $this->helper('Plumrocket\SocialLoginFree\Helper\Data');
            if($helper->modulePositionEnabled('login') && $helper->hasButtons()) : ?>
                <div class="pslogin-spacer pslogin-clearfix">
                    <table>
                        <tr>
                            <td><div class="pslogin-border"></div></td>
                            <td class="pslogin-bordertext w25"><?php echo __('OR'); ?></td>
                            <td><div class="pslogin-border"></div></td>
                        </tr>
                    </table>
                </div>
                <?php echo $this->getChildHtml('pslogin_buttons'); ?>
            <?php endif; ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('密碼') ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('密碼') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('密碼') ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="secondary forgot-password-link"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('忘記密碼?') ?></span></a></div>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('登入') ?></span></button></div>
                    <div class="secondary"><button type="button" onclick="window.location='<?php echo $block->getUrl('customer/account/create') ?>'" class="action create-account primary"><span><?php /* @escapeNotVerified */ echo __('註冊') ?></span></button></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
    ], function (jQuery) {
        jQuery( "#dialog-message" ).dialog({
            modal: true,
            width : 300,
            buttons: [
                {
                    text: "我知道了",
                    click: function() {
                        jQuery( this ).dialog( "close" );
                    }
                }
            ]
        });
    });
</script>
<div id="dialog-message" style="display:none;text-align: center;">
    <span style="font-size:30px">
        <font color="#E34132">重要公告請注意！</font> 
    </span> 
    <br/>
    <br/>
    <span style="font-size:1.5rem" >

        為確保您的客戶消費權益<br/>
        所有會員卡號<br/>
        皆需<span class="fwb fs16">實名驗證</span><br/>
        您的『<span class="fwb" >姓名</span>』與『<span class="fwb" >手機號碼</span>』<br/>
        <br/>
        ＊已完成驗證的帳號可直接登入。<br/>
        -------------------------<br/>
        若您於<span class="fwb fs16">實體門市</span>已有會員卡號<br/>
        <br/>
        登入後，請您驗證時確實填寫<br/>
        您在<span class="fwb fs16">實體門市</span>所註冊的<br/>
        『真實姓名』與『手機號碼』<br/>
        並進行驗證。<br/>
        -------------------------<br/>
        <br/>
        若您為官網會員<br/>
        請您確實填寫<br/>
        您的『真實姓名』與『手機號碼』<br/>
        並進行驗證<br/>
        <br/>
        <span style='text-decoration:underline;'> 完成驗證後在實體門市與官網<br/>
        即<span class="fwb fs16" >同時</span>擁有會員消費累積權益！</span>
     
    </span>
</div>