<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>
<div class="custom-title-wishlist"><h1><?php echo __('願望清單')?></h1></div>
<div class="products-grid wishlist">
    <?php $iterator = 1; ?>
    <?php if (count($block->getItems())): ?>
        <ol class="product-items">
            <?php foreach ($block->getItems() as $item):
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId());
                ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li data-row="product-item" class="product-item" id="item_' . $item->getId() . '">' : '</li><li class="product-item" id="item_' . $item->getId() . '">' ?>
                <div class="product-item-info <?php if($product->getTypeId() == 'configurable'){echo 'configurable';}?>">
                    <?php foreach ($columns as $column): ?>
                        <?php $column->setItem($item); echo $column->toHtml($item);?>
                    <?php endforeach; ?>
                </div>
                <?php echo($iterator == count($block->getItems())+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    <?php else: ?>
        <div class="message info empty">
            <span><?php /* @escapeNotVerified */ echo __('This Wish List has no Items');?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>

<script type="text/javascript">
    requirejs(['jquery'], function (jQuery) {
        jQuery(document).ready(function ($) {
            jQuery('ol.product-items li.product-item').each(function() {
                var choiceElement = jQuery(this).find('.product-item-tooltip');
                if (choiceElement.length == 0) {
                    jQuery(this).find('.product-item-info').addClass('content');
                }
            });
        });
    });
</script>
