<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue): ?>
    <div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
        <?php if ($_attributeLabel != 'none' && $_className != 'sku' && $_className != 'overview' && $_className != 'fitting-report'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>
        <?php if ($_attributeLabel != 'none' && $_className == 'overview'): ?><strong class="type"><?php /* @escapeNotVerified */ echo __('尺寸表(單位：公分)')?></strong><?php endif; ?>
        <?php if ($_className == 'description') : ?>
            <div class="block-title title">
                <strong id="block-descripion-heading" role="heading"><?php echo __('商品介紹') ?></strong>
            </div>
        <?php endif; ?>
        <?php if ($_attributeLabel != 'none' && $_className == 'overview'): ?><div class="sizechart-popup__close"><span>Close Popup</span></div><?php endif; ?>
        <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
    </div>
<?php endif; ?>
