<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php $i=0; foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title custom-title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     for="tab-<?php echo $i?>"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                    <?php if ($alias == 'product.info.short.desc') : ?>
                        <a class="size-table">tab</a>
                        <script type="text/javascript">
                            requirejs(['jquery'], function ($) {
                                $(document).ready(function () {
                                    $(".size-table").on('click', function () {
                                        var body = $('body');
                                        if (body.hasClass('sizechart-active')) {
                                            body.removeClass('sizechart-active');
                                        } else {
                                            body.addClass('sizechart-active');
                                        }
                                    });
                                    $(".sizechart-popup__close").on('click', function () {
                                        var body = $('body');
                                        if (body.hasClass('sizechart-active')) {
                                            body.removeClass('sizechart-active');
                                        }
                                    });
                                })
                                $(document).keyup(function(e) {
                                    if (e.keyCode === 27) {
                                        var body = $('body');
                                        if (body.hasClass('sizechart-active')) {
                                            body.removeClass('sizechart-active');
                                        }
                                    }
                                });
                            });
                        </script>
                    <?php endif; ?>
                </div>
                <div class="data item content custom-content tab-<?php echo $i?>" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php $i++; endforeach;?>
        </div>
    </div>

<?php endif; ?>

<script type="text/javascript">
    requirejs(['jquery'], function ($) {
        $(document).ready(function () {
            if ($(window).width() < 768) {
                $(".info .product div.custom-title").on('click', function () {
                    var attr = $(this).attr('for');
                    var element = $('.'+attr);

                    if($(this).hasClass('tab-active')){
                        element.removeClass('tab-active');
                        $(this).removeClass('tab-active');
                    } else {
                        $('.custom-title').each(function() {
                            if($(this).hasClass('tab-active')){
                                $(this).removeClass('tab-active');
                            }
                        });
                        $('.custom-content').each(function() {
                            if($(this).hasClass('tab-active')){
                                $(this).removeClass('tab-active');
                            }
                        });
                        element.addClass('tab-active');
                        $(this).addClass('tab-active');
                    }
                });

                $(".sizechart-popup__close").on('click', function () {
                    $('.custom-title').each(function() {
                        if($(this).hasClass('tab-active')){
                            $(this).removeClass('tab-active');
                        }
                    });
                    $('.custom-content').each(function() {
                        if($(this).hasClass('tab-active')){
                            $(this).removeClass('tab-active');
                        }
                    });
                });

            }
        })
    });
</script>
