<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty
 */
?>
<?php if ($block->isMsgVisible()): ?>
    <div class="availability only" title="<?php /* @escapeNotVerified */ echo __('最後%1組', ($block->getStockQtyLeft())) ?>">
        <?php /* @escapeNotVerified */ echo __('最後%1組', "<strong>{$block->getStockQtyLeft()}</strong>") ?>
    </div>
<?php endif ?>
