<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <?php
        $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
        $appState = $objectManager->get('\Magento\Framework\App\State');
        ?>

        <?php
        $productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
        $sku = $_item->getSku();
        try {
            $product = $productRepository->get($sku);
        } catch (Exception $e) {
            $product = null;
        }
        ?>
        <?php if ($product !== null) : ?>
            <?php
            $image = 'category_page_list';
            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
            $productImage = $_imagehelper->init($product, $image)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(1100,1570)->getUrl();
            ?>
            <div class="custom-product-image">
                <img class="product-image" alt="<?php echo $_item->getName(); ?>" src="<?php echo $productImage;?>">
            </div>
        <?php endif; ?>
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                    <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <dd>
                            <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                        </dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
